### PR TITLE
x/ref/lib/apilog: remove apilog

### PR DESCRIPTION
**Pull request by cosnicolaou**
Remove the apilog package and the associated logging of internal API calls since in practice they are too noisy to be useful.

### CODE REVIEW

**Comment by razvanm** [comment]
I found these logs rather hard to read but I did used them a few times to debug an understand what is going on in some parts of the code I was not familiar with (#22 that impacted the proxy is one example). The fact that I never actually use the apilog in the code I wrote did not help me getting more familiar with the package either.

**Comment by cosnicolaou** [comment]
are you arguing for keeping them?

I'm about to start on some pruning and this was an easy start. Are you interested in looking at and commenting on my broader TODO list?

**Comment by razvanm** [comment]
Correct, I argue for keeping this logging unless we have some other reasons. If the code is buggy or incorrect then I agree it make sense to remove it.

I'm happy to look at the TODO list. Can you point me to it? :-)

**Comment by cosnicolaou** [comment]
The main argument for getting rid of it is that it is noisy and out of date in that it doesn't cover everything that it should. I plan to overhaul logging in general so the less code to change the better. I'll post the todo list as an issue a little later today or tonight, it's currently in a personal google doc.

**Comment by razvanm** [comment]
Replacing the apilog with something better sounds great. Wouldn't be easier to keep the code around as a guide on what needs to convert to the new logging though?

**Pull request closed without merging**
