### PR TITLE
Add preliminary support for Windows

### PR DESCRIPTION
**Pull request by razvanm**
This gets the `V23_CREDENTIALS_NO_LOCK=1` mode to work. Most of the
changes consists in spliting out the code that doesn't work on Windows
and guarding it with appropriate `// build` tags and providing
`panic("not implemented")` implementations for Windows.

### CODE REVIEW

**Comment by razvanm** [comment]
Where can I see the comment? I reverted the changes to the principal/main.go and namespace/impl.go and only them those internally.

```
$ git diff HEAD^ -- x/ref/cmd/namespace/impl.go x/ref/cmd/principal/main.go 
diff --git a/x/ref/cmd/namespace/impl.go b/x/ref/cmd/namespace/impl.go
index 3e654d9..831dee9 100644
--- a/x/ref/cmd/namespace/impl.go
+++ b/x/ref/cmd/namespace/impl.go
@@ -27,7 +27,7 @@ import (
        "v.io/v23/verror"
 
        "v.io/x/ref/lib/v23cmd"
-       _ "v.io/x/ref/runtime/factories/generic"
+       _ "v.io/x/ref/runtime/factories/grail"
 )
 
 func main() {
diff --git a/x/ref/cmd/principal/main.go b/x/ref/cmd/principal/main.go
index 2858944..a9d0b53 100644
--- a/x/ref/cmd/principal/main.go
+++ b/x/ref/cmd/principal/main.go
@@ -32,7 +32,7 @@ import (
        vsecurity "v.io/x/ref/lib/security"
        "v.io/x/ref/lib/security/passphrase"
        "v.io/x/ref/lib/v23cmd"
-       _ "v.io/x/ref/runtime/factories/roaming"
+       _ "v.io/x/ref/runtime/factories/grail"
 )
 
 var (
```

**Comment by razvanm** [comment]
Ping...

**Comment by cosnicolaou** [comment]
I think I made the comment on the changed file in one of the pull requests. I think we should simply create a new factory that's local to the core repo rather than using the grail one? Let's chat tomorrow AM.

**Comment by cosnicolaou** [comment]
I'm going to close this since I'll be making a more concerted attempt to run on windows over the coming months and have already ported the x/ref/lib repo.

**Pull request closed without merging**
